services:
  moodle:
    build: .
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_MOODLE_80
      - MOODLE_DB_HOST=${MOODLE_DB_HOST}
      - MOODLE_DB_NAME=${MOODLE_DB_NAME}
      - MOODLE_DB_USER=${MOODLE_DB_USER}
      - MOODLE_DB_PASSWORD=${MOODLE_DB_PASSWORD}
      - MOODLE_WWWROOT=${MOODLE_WWWROOT}
    volumes:
      - moodledata:/var/moodledata

  moodle-cron:
    build: .
    restart: unless-stopped
    environment:
      - MOODLE_DB_HOST=${MOODLE_DB_HOST}
      - MOODLE_DB_NAME=${MOODLE_DB_NAME}
      - MOODLE_DB_USER=${MOODLE_DB_USER}
      - MOODLE_DB_PASSWORD=${MOODLE_DB_PASSWORD}
      - MOODLE_WWWROOT=${MOODLE_WWWROOT}
    volumes:
      - moodledata:/var/moodledata
    entrypoint: /bin/bash
    command: -c "/entrypoint.sh true; while true; do php /var/www/html/admin/cli/cron.php; sleep 60; done"

volumes:
  moodledata:

networks:
  default:
    name: dqugrtlz6te9fp3f5qkwoqer
    external: true